#!/usr/bin/env bash
# Reproducible packaging: no runtime pip, uv or system Python required.
# Distribution target: Linux x86_64, compatible glibc, NVIDIA driver for cu117.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$ROOT/src/python/.venv"
PYTHON_PATH="$(readlink -f "$VENV/bin/python")"
PYTHON_ROOT="$(cd "$(dirname "$PYTHON_PATH")/.." && pwd)"
OUTPUT="${1:-/kaggle/working/piper-neo-studio-linux-x86_64-py310-cu117.tar.gz}"
if [[ ! -x "$PYTHON_PATH" ]]; then echo "Run setup_kaggle_finetune.sh first." >&2; exit 2; fi
if [[ "$(uname -m)" != "x86_64" ]]; then echo "Build must be x86_64 Linux." >&2; exit 2; fi
if [[ ! -d "$VENV/lib/python3.10/site-packages" ]]; then echo "Missing site-packages." >&2; exit 2; fi
if [[ ! -f "$ROOT/src/python/piper_train/vits/monotonic_align/monotonic_align/core"*.so ]]; then
  echo "Warning: compiled monotonic_align extension not found at expected path" >&2
fi
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/piper-neo-studio/app"
ln -s "$PYTHON_ROOT" "$STAGE/piper-neo-studio/python"
ln -s "$VENV/lib/python3.10/site-packages" "$STAGE/piper-neo-studio/site-packages"
ln -s "$ROOT/src/python/piper_train" "$STAGE/piper-neo-studio/app/piper_train"
cp "$ROOT/script/piper_studio_launch.sh" "$STAGE/piper-neo-studio/run.sh"
chmod +x "$STAGE/piper-neo-studio/run.sh"
"$VENV/bin/python" -m pip freeze > "$STAGE/piper-neo-studio/pip-freeze.txt" 2>/dev/null || true
cat > "$STAGE/piper-neo-studio/README.txt" <<'EOF'
Piper Neo Studio Portable
Linux x86_64 / Python 3.10 / PyTorch 1.13.1 cu117
Unpack: tar -xzf piper-neo-studio-linux-x86_64-py310-cu117.tar.gz
Run: ./piper-neo-studio/run.sh --share --port 7860
This runtime bundles its Python interpreter and dependencies and imports local source.
The host must supply compatible glibc and NVIDIA driver+GPU for CUDA acceleration.
Data/checkpoints/HF credentials are not included. Do NOT expose share links without auth.
EOF
mkdir -p "$(dirname "$OUTPUT")"
echo "Packing $OUTPUT (approx. 4GB uncompressed, may take several minutes)"
# Follow the three staging symlinks into real content, avoiding a second 4GB copy.
# Exclude generated bytecode, caches, tests, static include headers, and editable .pth paths.
tar -C "$STAGE" --dereference \
  --exclude='__pycache__' --exclude='*.pyc' \
  --exclude='*/tests/*' --exclude='*/test/*' \
  --exclude='*/torch/include/*' --exclude='*/nvidia/*/include/*' \
  -cf - piper-neo-studio | gzip -1 > "$OUTPUT"
sha256sum "$OUTPUT" | tee "$OUTPUT.sha256"
echo "Bundle created: $OUTPUT"
